OPENEUROPA-3251: Initialize Open Vocabularies component.
openeuropa/open_vocabularies pull request #1
Opened 2020-06-03 13:30 UTC by 22Alexandra

2020-06-04 07:48 UTC, nagyad requested changes

2020-06-04 07:48 UTC, nagyad commented on composer.json
> +        "drush/drush": "~9.0@stable",
"9.x-dev#93075ab"

2020-06-04 07:48 UTC, nagyad commented on composer.json
> +        "openeuropa/code-review": "~1.0.0-beta2",
"^1.3.0"

2020-06-04 07:48 UTC, nagyad commented on composer.json
> +        "openeuropa/drupal-core-require-dev": "^8.7",
"^8.8"

2020-06-04 07:48 UTC, nagyad commented on open_vocabularies.info.yml
> +description: Open Vocabularies component.
Could we collect some meaningful description here?

2020-06-04 07:48 UTC, nagyad commented on open_vocabularies.module
> +declare(strict_types = 1);
Remove this file, we will add it once we need it.

2020-06-04 08:19 UTC, nagyad commented on open_vocabularies.info.yml
> +description: Open Vocabularies component.
Use a sentence from the readme.

2020-06-04 09:16 UTC, nagyad submitted a review, later dismissed

2020-06-08 08:36 UTC, ademarco requested changes

2020-06-08 08:36 UTC, ademarco commented on README.md
> +It provides a field type that can be added to fieldable entities. Then associations between the vocabularies and the field instances can be created, allowing to categorise the content in a flexible w
Shall we try with something like this?

The Open Vocabularies module allows users to choose how a piece of content will be categorised without having to change the related content type field definition.
It does that by providing:

- An open vocabulary field type
- The possibility to create associations between open vocabulary field types and Drupal categorisation systems, such as Drupal taxonomies, Publication Office vocabularies, or subsets of them.

In other words: once a content type is equipped with an open vocabulary field, users with appropriate access can decide which type of entities that field will able to referencing, by creating associations.

2020-06-08 08:36 UTC, ademarco commented on composer.json
> +    "description": "Open Vocabularies component.",
Let's use this one maybe:
```
Choose how a piece of content will be categorised without having to change the related content type field definition.
```

2020-06-08 08:39 UTC, ademarco requested changes

2020-06-08 08:39 UTC, ademarco commented on composer.json
> +        "drush/drush": "9.x-dev#93075ab",
We can now use ~9.0

2020-06-08 08:39 UTC, ademarco commented on open_vocabularies.info.yml
> +description: The Open Vocabularies component allows you to create “open” vocabularies that wrap categorisation systems, like Drupal taxonomies or Publication Office vocabularies, or subsets of them.
Let's reuse the same on composer.json:
```
Choose how a piece of content will be categorised without having to change the related content type field definition.
```

2020-06-08 12:00 UTC, ademarco approved these changes

2020-06-08 12:01 UTC, nagyad approved these changes

2020-06-08 12:08 UTC, merged