EWPP-653: Allow to select additional fields for associations.
openeuropa/open_vocabularies pull request #21
Opened 2021-01-20 07:50 UTC by brummbar

2021-01-20 10:06 UTC, upchuk requested changes

2021-01-20 10:06 UTC, upchuk commented on src/Form/OpenVocabularyAssociationForm.php
> +            '@field' => $field_label,
Let's not print the field name if we have only 1 field on the bundle as it is not valuable for anyone. We can print in case there are 2 fields on the same bundle which is anyway expected to be a rare occasion.

2021-01-21 07:56 UTC, upchuk approved these changes

2021-01-22 15:01 UTC, 22Alexandra approved these changes

2021-02-03 10:34 UTC, merged