OEL-165: Drupal 9 compatibility fixes.
openeuropa/open_vocabularies pull request #28
Opened 2021-06-04 13:50 UTC by saidatom

2021-06-10 12:57 UTC, nagyad approved these changes, later dismissed

2021-06-10 15:33 UTC, sergepavle reviewed
On try to rerun upgrade status I still have this message:

```
FILE:
modules/custom/open_vocabularies/tests/src/Functional/OpenVocabularyAdminTest.ph
p

STATUS         LINE                           MESSAGE                           
--------------------------------------------------------------------------------
Fix now        152  Call to deprecated method assertUrl() of class              
                    Drupal\Tests\BrowserTestBase. Deprecated in drupal:8.2.0 and
                    is removed from drupal:10.0.0. Use                          
                    $this->assertSession()->addressEquals() instead.            
--------------------------------------------------------------------------------
```
Can you take a look at this message?

2021-06-11 09:56 UTC, sergepavle approved these changes, later dismissed

2021-06-11 09:58 UTC, nagyad approved these changes, later dismissed

2021-06-16 08:01 UTC, brummbar requested changes

2021-06-16 08:01 UTC, brummbar commented on composer.json
> +        "drupal/drupal-extension": "~4.0",
This was 4.1 minimum, is there a reason to lower it? Also use ^ as before.

2021-06-16 08:01 UTC, brummbar commented on composer.json
> +        "openeuropa/behat-transformation-context" : "~0.1",
Why this was added? It's not used.

2021-06-16 08:01 UTC, brummbar commented on composer.json
> +        "openeuropa/code-review": "~1.6",
Use ^ as it was before.

2021-06-16 08:01 UTC, brummbar commented on open_vocabularies.info.yml
> +core_version_requirement: ^8 || ^9
Since we are now putting compatibility to ^8.9 || ^9.1 in composer.json, we can reflect that here.

2021-06-16 08:01 UTC, brummbar commented on tests/modules/open_vocabularies_test/open_vocabularies_test.info.yml
> +core_version_requirement: ^8 || ^9
Same as above.

2021-06-16 08:01 UTC, brummbar commented on tests/src/Kernel/VocabularyReferenceFieldsManagerTest.php
> +    $this->assertSame([
Use `assertEquals` in all of these. The scope is to check the content of the array, not the exact order.

2021-06-16 13:51 UTC, brummbar requested changes
The changes are good, but you force-pushed the last changes on top of a commit which talks about changing a deprecated method. We need to take care about commit messages and git history :) 
Please repush the last commit as it was before, add a new (or multiple ones) that fix the review comments. Try to avoid as much as possible a "Fix QA remarks", rather use something more meaningful like "Cleanup dev dependencies" or similar, and "change assertion methods", and "update core version requirements to match composer.json", etc.

2021-06-21 14:57 UTC, nagyad approved these changes

2021-06-21 15:35 UTC, sergepavle approved these changes

2021-06-24 15:24 UTC, brummbar approved these changes

2021-06-29 15:28 UTC, merged