EWPP-1749: Cache tags for vocabulary associations on json api.
openeuropa/open_vocabularies pull request #36
Opened 2022-04-13 16:53 UTC by yenyasinn

2022-04-20 15:14 UTC, nagyad requested changes
We need to find a way to cover this code with tests.

2022-04-22 09:06 UTC, nagyad requested changes

2022-04-22 09:06 UTC, nagyad commented on tests/src/Kernel/EntityAccessTest.php
> + * Tests the computed field item list class.
Fix this comment.

2022-04-22 09:06 UTC, nagyad commented on open_vocabularies.module
> +  }
Let's document why we need to this like this.

2022-04-22 11:35 UTC, nagyad submitted a review, later dismissed

2022-04-25 12:39 UTC, imanoleguskiza approved these changes, later dismissed

2022-04-26 07:37 UTC, brummbar requested changes
Queueing myself for review.

2022-05-03 07:43 UTC, yenyasinn commented on src/OpenVocabularyAssociationStorage.php
> +        Cache::invalidateTags($entity_type->getListCacheTags());
Don't we need to update `/node/nid` and `/jsonapi/node/[bundle]/[uid]` pages? These pages don't contain list tags

2022-05-05 07:37 UTC, hernani commented
Should be closed

2022-05-05 13:37 UTC, closed without merging