EWPP-2796: Allow higher number of allowed values for association.
openeuropa/open_vocabularies pull request #43
Opened 2022-11-21 11:19 UTC by nagyad

2022-11-21 13:08 UTC, 22Alexandra requested changes

2022-11-21 13:08 UTC, 22Alexandra commented on src/Form/OpenVocabularyAssociationForm.php
> +      $form_state->setErrorByName('cardinality_number', $this->t("Number of values can't be smaller than the previously set number: %value.", ['%value' => $this->original->getCardinality()]));
```suggestion
      $form_state->setErrorByName('cardinality_number', $this->t('Number of values can\'t be smaller than the previously set number: %value.', ['%value' => $this->original->getCardinality()]));
```

2022-11-21 13:08 UTC, 22Alexandra commented on src/Form/OpenVocabularyAssociationForm.php
> +    if ($form_state->getValue('cardinality') != '-1' && $this->original->getCardinality() > $form_state->getValue('cardinality_number')) {
```suggestion
    if ($form_state->getValue('cardinality') !== '-1' && $this->original->getCardinality() > $form_state->getValue('cardinality_number')) {
```

2022-11-21 16:06 UTC, imanoleguskiza submitted a review, later dismissed

2022-11-22 09:56 UTC, nagyad commented on src/Form/OpenVocabularyAssociationForm.php
> +      $form_state->setErrorByName('cardinality_number', $this->t("Number of values can't be smaller than the previously set number: %value.", ['%value' => $this->original->getCardinality()]));
PHPCS suggested to use double quote instead of backslash.

2022-11-22 09:56 UTC, nagyad commented on src/Form/OpenVocabularyAssociationForm.php
> +    if ($form_state->getValue('cardinality') != '-1' && $this->original->getCardinality() > $form_state->getValue('cardinality_number')) {
Using non type strict comparison because it can come back as a string or int.

2022-11-25 07:52 UTC, 22Alexandra approved these changes, later dismissed

2022-11-29 09:38 UTC, upchuk requested changes

2022-11-29 09:38 UTC, upchuk commented on src/Form/OpenVocabularyAssociationForm.php
> +      '#disabled' => $entity->getCardinality() == -1,
Use the constant for cardinality unlimited (everywhere), and `===`)

2022-11-29 14:57 UTC, 22Alexandra approved these changes

2022-11-29 14:59 UTC, upchuk approved these changes
Approving for imanol

2022-11-29 14:59 UTC, merged